---
version: '2'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #mem_limit: ${MEM_LIMIT}
    command: --max-connections=${MAX_CONNECTIONS}
    volumes:
      - mysqldata:/var/lib/mysql

  lb:
    image: rancher/lb-service-haproxy:v0.4.9
    ports: ${MYSQL_EXPORT_PORT}:3306
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'


volumes:
  mysqldata:
    driver: rancher-lvmnfs
    driver_opts:
      size: ${QUOTA_SIZE_MIB}
